name: another_workaround_for_case2
run-name: another around for case2 with is-skip-jobA is ${{ inputs.is-skip-jobA }}
on:
  workflow_dispatch:
    inputs:
      is-skip-jobA:
        description: "Skip job A?"
        required: true
        default: false
        type: boolean

jobs:
  jobA:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - run: echo "jobA"
        if: ${{ !inputs.is-skip-jobA }}
  jobB:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - run: echo "jobB"
  jobC:
    needs: [jobA, jobB]
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - run: echo "jobC"
  jobD:
    needs: jobC
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - run: echo "jobD"
